-- 0014 — Teklifler ve damga vergisi defteri (yalnız ekleme; mevcut satır ve politika değişmez).
-- Teklif kabul edilince convert_quote() müşteri, sözleşme, ilk fatura ve damga vergisi kaydını TEK işlemde açar:
-- biri başarısız olursa hiçbiri yazılmaz. Fonksiyon çağıranın yetkisiyle çalışır (RLS geçerli) ve yalnız personele açıktır.

-- Teklif: fiyatlar dönem başına (aylık/yıllık) KDV dahildir; sözleşme süresi ay olarak tutulur.
create table if not exists public.quotes(
  id uuid primary key default gen_random_uuid(),
  number bigint generated by default as identity unique,
  title text not null check (length(btrim(title)) > 0),
  contact text,
  email text,
  phone text,
  tax_no text,
  tc text,
  tax_office text,
  package text not null,
  billing_period text not null default 'yıllık' check (billing_period in ('aylık','yıllık')),
  term_months integer not null default 12 check (term_months between 1 and 60),
  list_price numeric not null default 0 check (list_price >= 0),
  discount_pct numeric not null default 0 check (discount_pct >= 0 and discount_pct <= 100),
  price numeric not null check (price > 0),
  bni boolean not null default false,
  valid_until date,
  status text not null default 'taslak' check (status in ('taslak','gönderildi','kabul','red')),
  notes text,
  customer_id uuid references public.customers(id) on delete set null,
  contract_id uuid references public.contracts(id) on delete set null,
  sent_at timestamptz,
  decided_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists quotes_status_created_idx on public.quotes(status, created_at desc);

-- Damga vergisi defteri: her imza ya da yenileme ayrı satırdır (vergiyi doğuran olay belge tarihidir).
-- Taraf ünvanı/VKN kayıt anında kopyalanır; müşteri silinse de beyan kaydı okunur kalır.
-- Tutar = matrah × oran (binde) × imzalı nüsha sayısı; elle girilmez, hesaplanır.
create table if not exists public.stamp_taxes(
  id uuid primary key default gen_random_uuid(),
  customer_id uuid references public.customers(id) on delete set null,
  contract_id uuid references public.contracts(id) on delete set null,
  party_title text not null check (length(btrim(party_title)) > 0),
  party_tax_id text,
  kind text not null default 'sözleşme' check (kind in ('sözleşme','yenileme')),
  doc_date date not null,
  period_start date,
  period_end date,
  base numeric not null check (base > 0),
  rate_per_mille numeric not null default 9.48 check (rate_per_mille > 0 and rate_per_mille <= 20),
  copies integer not null default 1 check (copies between 1 and 10),
  amount numeric generated always as (round(base * rate_per_mille * copies / 1000, 2)) stored,
  payer text not null default 'müşteri' check (payer in ('müşteri','GANU','yarı yarıya')),
  collected_at date,
  declared_period text check (declared_period ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'),
  notes text,
  created_at timestamptz not null default now(),
  constraint stamp_taxes_period_order check (period_start is null or period_end is null or period_end >= period_start)
);
create index if not exists stamp_taxes_doc_date_idx on public.stamp_taxes(doc_date);
create index if not exists stamp_taxes_contract_idx on public.stamp_taxes(contract_id);

alter table public.quotes enable row level security;
alter table public.stamp_taxes enable row level security;
drop policy if exists "staff_all_quotes" on public.quotes;
create policy "staff_all_quotes" on public.quotes for all to authenticated using (public.is_staff()) with check (public.is_staff());
drop policy if exists "staff_all_stamp_taxes" on public.stamp_taxes;
create policy "staff_all_stamp_taxes" on public.stamp_taxes for all to authenticated using (public.is_staff()) with check (public.is_staff());
revoke all on public.quotes, public.stamp_taxes from anon;
grant select, insert, update, delete on public.quotes, public.stamp_taxes to authenticated;
grant usage, select on sequence public.quotes_number_seq to authenticated;

-- İşlem kaydı (0013) bu tablolarda da tutulur.
drop trigger if exists audit_row on public.quotes;
create trigger audit_row after insert or update or delete on public.quotes for each row execute function public.audit_row();
drop trigger if exists audit_row on public.stamp_taxes;
create trigger audit_row after insert or update or delete on public.stamp_taxes for each row execute function public.audit_row();

-- Teklifi müşteriye dönüştürür. p_customer.id doluysa mevcut müşteri kullanılır, değilse yeni müşteri açılır.
-- p_invoice ve p_stamp isteğe bağlıdır (null → açılmaz). Dönüş: oluşan kayıtların id'leri.
create or replace function public.convert_quote(p_quote uuid, p_customer jsonb, p_contract jsonb, p_invoice jsonb default null, p_stamp jsonb default null)
returns jsonb language plpgsql security invoker set search_path=public,pg_catalog as $$
declare
  q public.quotes; cu public.customers; ct public.contracts; inv public.invoices; st public.stamp_taxes;
  c_id uuid; k_id uuid; i_id uuid; s_id uuid;
begin
  if not public.is_staff() then raise exception 'Yetkisiz' using errcode = '42501'; end if;
  select * into q from public.quotes where id = p_quote for update;
  if not found then raise exception 'Teklif bulunamadı'; end if;
  if q.contract_id is not null then raise exception 'Bu teklif zaten müşteriye dönüştürülmüş'; end if;
  if q.status = 'red' then raise exception 'Reddedilmiş teklif dönüştürülemez'; end if;

  if nullif(p_customer->>'id', '') is not null then
    c_id := (p_customer->>'id')::uuid;
    if not exists (select 1 from public.customers where id = c_id) then raise exception 'Müşteri bulunamadı'; end if;
  else
    cu := jsonb_populate_record(null::public.customers, p_customer - 'id');
    insert into public.customers(title, contact, email, phone, tax_no, tc, tax_office, address, city, district, status, partner_id, bni, notes)
    values (cu.title, cu.contact, cu.email, cu.phone, cu.tax_no, cu.tc, cu.tax_office, cu.address, cu.city, cu.district,
            coalesce(cu.status, 'aktif'), cu.partner_id, coalesce(cu.bni, q.bni, false), cu.notes)
    returning id into c_id;
  end if;

  ct := jsonb_populate_record(null::public.contracts, p_contract);
  insert into public.contracts(customer_id, package, billing_period, start_date, end_date, price, status, auto_renew)
  values (c_id, coalesce(ct.package, q.package), coalesce(ct.billing_period, q.billing_period), ct.start_date, ct.end_date,
          coalesce(ct.price, q.price), 'aktif', coalesce(ct.auto_renew, false))
  returning id into k_id;

  if p_invoice is not null then
    inv := jsonb_populate_record(null::public.invoices, p_invoice);
    if coalesce(inv.amount, 0) <= 0 then raise exception 'Fatura tutarı sıfırdan büyük olmalı'; end if;
    insert into public.invoices(customer_id, contract_id, amount, issue_date, due_date, status, note)
    values (c_id, k_id, inv.amount, coalesce(inv.issue_date, current_date), inv.due_date, 'bekliyor', inv.note)
    returning id into i_id;
  end if;

  if p_stamp is not null then
    st := jsonb_populate_record(null::public.stamp_taxes, p_stamp);
    insert into public.stamp_taxes(customer_id, contract_id, party_title, party_tax_id, kind, doc_date, period_start, period_end,
                                   base, rate_per_mille, copies, payer, notes)
    select c_id, k_id, c.title, coalesce(nullif(c.tax_no, ''), nullif(c.tc, '')), 'sözleşme', coalesce(st.doc_date, current_date),
           coalesce(st.period_start, ct.start_date), coalesce(st.period_end, ct.end_date), st.base, coalesce(st.rate_per_mille, 9.48),
           coalesce(st.copies, 1), coalesce(st.payer, 'müşteri'), st.notes
      from public.customers c where c.id = c_id
    returning id into s_id;
  end if;

  update public.quotes set status = 'kabul', customer_id = c_id, contract_id = k_id, decided_at = coalesce(decided_at, now())
   where id = p_quote;
  return jsonb_build_object('customer_id', c_id, 'contract_id', k_id, 'invoice_id', i_id, 'stamp_tax_id', s_id);
end $$;
revoke all on function public.convert_quote(uuid, jsonb, jsonb, jsonb, jsonb) from public, anon;
grant execute on function public.convert_quote(uuid, jsonb, jsonb, jsonb, jsonb) to authenticated;
