import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const SITE=Deno.env.get('SITE_URL')||''; let ORIGIN=''
try { ORIGIN=SITE?new URL(SITE).origin:'' } catch { ORIGIN='' }
const cors={...(ORIGIN?{'Access-Control-Allow-Origin':ORIGIN}:{}),'Access-Control-Allow-Headers':'authorization,x-client-info,apikey,content-type','Access-Control-Allow-Methods':'POST,OPTIONS'}
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,'Content-Type':'application/json'}})
const enc=new TextEncoder(); const dec=new TextDecoder()
class AppError extends Error{constructor(public status:number,message:string){super(message)}}

function admin(){const u=Deno.env.get('SUPABASE_URL'),k=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!u||!k)throw new Error('Supabase secret eksik');return createClient(u,k,{auth:{persistSession:false}})}
function secret(){const s=Deno.env.get('PURCHASE_FLOW_SECRET')||'';if(s.length<32)throw new Error('PURCHASE_FLOW_SECRET en az 32 karakter olmalı');return s}
function legalVersion(){const v=Deno.env.get('LEGAL_TEXT_VERSION')||'';if(v!=='2026-08-15.v1')throw new Error('LEGAL_TEXT_VERSION eksik/geçersiz');return v}
function ip(req:Request){const raw=(req.headers.get('x-forwarded-for')||'').split(',')[0].trim();if(!/^([0-9a-f:.]{3,45})$/i.test(raw))throw new Error('güvenilir istemci IP başlığı yok');return raw}
const hex=(b:ArrayBuffer)=>[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')
async function keyedHash(domain:'legal-ip'|'legal-ua'|'rate-limit-ip',value:string){const k=await crypto.subtle.importKey('raw',enc.encode(secret()),{name:'HMAC',hash:'SHA-256'},false,['sign']);return hex(await crypto.subtle.sign('HMAC',k,enc.encode(`${domain}\0${value}`)))}
const b64u=(b:Uint8Array)=>btoa(String.fromCharCode(...b)).replaceAll('+','-').replaceAll('/','_').replace(/=+$/,'')
const unb64u=(s:string)=>Uint8Array.from(atob(s.replaceAll('-','+').replaceAll('_','/')+'==='.slice((s.length+3)%4)),c=>c.charCodeAt(0))
async function sign(msg:string){const k=await crypto.subtle.importKey('raw',enc.encode(secret()),{name:'HMAC',hash:'SHA-256'},false,['sign']);return b64u(new Uint8Array(await crypto.subtle.sign('HMAC',k,enc.encode(msg))))}
async function validSig(msg:string,sig:string){try{const k=await crypto.subtle.importKey('raw',enc.encode(secret()),{name:'HMAC',hash:'SHA-256'},false,['verify']);return await crypto.subtle.verify('HMAC',k,unb64u(sig),enc.encode(msg))}catch{return false}}
type P={v:number;sid:string;cid:string;pkg:string;amt:number;pv:number;disc:string;lv:string;exp:number}
async function token(p:P){const body=b64u(enc.encode(JSON.stringify(p)));return `${body}.${await sign(body)}`}
async function verify(t:string):Promise<P>{try{const [body,sig,extra]=String(t||'').split('.');if(!body||!sig||extra||!await validSig(body,sig))throw new Error();const p=JSON.parse(dec.decode(unb64u(body))) as P,uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;if(p.v!==2||p.lv!==legalVersion()||!uuid.test(String(p.sid))||!uuid.test(String(p.cid))||typeof p.pkg!=='string'||typeof p.disc!=='string'||!Number.isFinite(Number(p.amt))||!Number.isInteger(Number(p.pv))||!Number.isFinite(Number(p.exp)))throw new Error();if(Date.now()>=Number(p.exp)*1000)throw new AppError(400,'purchase token süresi dolmuş');return p}catch(e){if(e instanceof AppError)throw e;throw new AppError(400,'purchase token geçersiz')}}
async function limited(db:ReturnType<typeof admin>,req:Request,action:'create'|'claim'){const h=await keyedHash('rate-limit-ip',ip(req));const {data,error}=await db.rpc('purchase_rate_limit',{p_ip_hash:h,p_action:action,p_limit:action==='create'?5:10,p_window_seconds:3600});if(error)throw new Error('rate-limit DB hatası');if(data!==true)throw new AppError(429,'çok fazla istek')}

async function quote(db:ReturnType<typeof admin>,pkgId:string,rawCode:string){const {data:p,error}=await db.from('packages').select('id,list_amount,price_version,is_custom,active,currency').eq('id',pkgId).maybeSingle();if(error)throw new Error('fiyat kataloğu DB hatası');if(!p||!p.active)throw new AppError(400,'paket geçersiz');const list=Number(p.list_amount)||0;let pct=0,code='';const norm=String(rawCode||'').trim().toUpperCase().replace(/\s+/g,'');if(norm){const {data:d,error:e}=await db.from('discount_codes').select('pct,active').eq('code',norm).maybeSingle();if(e)throw new Error('indirim DB hatası');if(d?.active){pct=Number(d.pct)||0;code=norm}}const amount=p.is_custom?0:Math.round(list*(100-pct))/100;if(!p.is_custom&&amount<=0)throw new Error('katalog fiyatı geçersiz');return{pkg:p.id,list,amount,pv:Number(p.price_version)||1,pct,code,currency:p.currency||'TL',custom:!!p.is_custom}}
function validFile(file:File){if(file.size<=0||file.size>8*1024*1024)throw new AppError(400,'dosya en fazla 8 MB olmalı');const ok=['image/jpeg','image/png','image/webp','application/pdf'];if(!ok.includes(file.type))throw new AppError(400,'yalnız JPEG/PNG/WebP/PDF');}
async function magic(file:File){const b=new Uint8Array(await file.slice(0,12).arrayBuffer());const pdf=dec.decode(b.slice(0,4))==='%PDF',jpg=b[0]===255&&b[1]===216&&b[2]===255,png=[137,80,78,71,13,10,26,10].every((x,i)=>b[i]===x),webp=dec.decode(b.slice(0,4))==='RIFF'&&dec.decode(b.slice(8,12))==='WEBP';if(!({"application/pdf":pdf,"image/jpeg":jpg,"image/png":png,"image/webp":webp} as Record<string,boolean>)[file.type])throw new AppError(400,'dosya imzası MIME ile uyuşmuyor')}
async function session(db:ReturnType<typeof admin>,p:P){const {data,error}=await db.from('purchase_sessions').select('id,customer_id,package_id,amount,price_version,discount_code,expires_at,claimed_at,legal_text_version,preinfo_accepted_at,early_performance_requested_at,customers!inner(status)').eq('id',p.sid).eq('customer_id',p.cid).maybeSingle();if(error)throw new Error('session DB hatası');const linked=Array.isArray(data?.customers)?data.customers[0]:data?.customers;if(!data||linked?.status!=='aday')throw new AppError(409,'satın alma oturumu yok');if(data.package_id!==p.pkg||Number(data.amount)!==Number(p.amt)||Number(data.price_version)!==Number(p.pv)||(data.discount_code||'')!==p.disc||data.legal_text_version!==p.lv||!data.preinfo_accepted_at||!data.early_performance_requested_at||Date.now()>=new Date(data.expires_at).getTime())throw new AppError(409,'satın alma oturumu uyuşmuyor');return data}

Deno.serve(async(req)=>{if(!ORIGIN)return json({error:'SITE_URL yapılandırılmadı'},500);const o=req.headers.get('origin')||'';if(o&&o!==ORIGIN)return json({error:'Origin izinli değil'},403);if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({error:'POST kullanın'},405)
 try{const db=admin();secret();legalVersion();const ct=req.headers.get('content-type')||''
  if(ct.includes('multipart/form-data')){await limited(db,req,'claim');const f=await req.formData(),p=await verify(String(f.get('purchase_token')||'')),file=f.get('file');if(!(file instanceof File))throw new AppError(400,'dosya gerekli');await session(db,p);validFile(file);await magic(file);const ext=({"application/pdf":"pdf","image/jpeg":"jpg","image/png":"png","image/webp":"webp"} as Record<string,string>)[file.type],path=`receipts/${p.cid}/${crypto.randomUUID()}.${ext}`;const {error:ue}=await db.storage.from('secure-docs').upload(path,file,{contentType:file.type,upsert:false});if(ue)throw ue;const {data:ok,error}=await db.rpc('purchase_record_claim',{p_session:p.sid,p_customer:p.cid,p_receipt:`secure:${path}`,p_sender:String(f.get('sender')||'')});if(error){await db.storage.from('secure-docs').remove([path]);throw error}if(ok!==true){await db.storage.from('secure-docs').remove([path]);throw new AppError(409,'bildirim daha önce işlendi')}return json({ok:true,receipt:true})}
  const b=await req.json();if(b.action==='create'){await limited(db,req,'create');const lv=legalVersion();if(b.legal_text_version!==lv||b.preinfo_accepted!==true||b.early_performance_requested!==true)throw new AppError(400,'zorunlu hukuki bilgilendirme/erken ifa kanıtı eksik');const q=await quote(db,String(b.package_id||''),String(b.code||''));const title=String(b.title||'').trim().slice(0,200),email=String(b.email||'').trim().toLowerCase().slice(0,254),phone=String(b.phone||'').replace(/[^0-9+]/g,'').slice(0,16),tax=String(b.tax_no||'').replace(/\D/g,''),ref=String(b.ref||'').trim().toUpperCase().replace(/[^A-Z0-9_-]/g,'').slice(0,32);const emailOk=!email||/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(email),phoneDigits=phone.replace(/\D/g,'');if(!title||(!email&&!phone)||!emailOk||(phone&&!(phoneDigits.length>=10&&phoneDigits.length<=13))||(!q.custom&&![10,11].includes(tax.length)))throw new AppError(400,'başvuru alanları geçersiz');const cid=crypto.randomUUID(),sid=crypto.randomUUID(),exp=Math.floor(Date.now()/1000)+1800,rawIp=ip(req),ipHash=await keyedHash('legal-ip',rawIp),uaHash=await keyedHash('legal-ua',req.headers.get('user-agent')||'');const {data:ok,error}=await db.rpc('purchase_create_candidate_legal',{p_customer:cid,p_session:sid,p_title:title,p_email:email,p_phone:phone,p_tax_no:tax.length===10?tax:'',p_tc:tax.length===11?tax:'',p_tax_office:String(b.tax_office||'').trim().slice(0,100),p_ref:ref,p_bni:q.code==='BNINISANTASI',p_package:q.pkg,p_amount:q.amount,p_list:q.list,p_price_version:q.pv,p_discount_code:q.code,p_discount_pct:q.pct,p_currency:q.currency,p_expires_at:new Date(exp*1000).toISOString(),p_legal_text_version:lv,p_preinfo_accepted:true,p_early_performance_requested:true,p_ip_hash:ipHash,p_user_agent_hash:uaHash});if(error||ok!==true)throw new Error('aday kaydı oluşturulamadı');const t=await token({v:2,sid,cid,pkg:q.pkg,amt:q.amount,pv:q.pv,disc:q.code,lv,exp});return json({customer:{id:cid,title,email,phone,status:'aday'},purchase_token:t,quote:{amount:q.amount,list_amount:q.list,discount_code:q.code,discount_pct:q.pct,price_version:q.pv,currency:q.currency,is_custom:q.custom},expires_at:exp})}
  if(b.action==='claim'){await limited(db,req,'claim');const p=await verify(String(b.purchase_token||''));await session(db,p);const {data:ok,error}=await db.rpc('purchase_record_claim',{p_session:p.sid,p_customer:p.cid,p_receipt:'',p_sender:String(b.sender||'')});if(error)throw error;if(ok!==true)throw new AppError(409,'bildirim daha önce işlendi');return json({ok:true,receipt:false})}
  return json({error:'bilinmeyen action'},400)
 }catch(e){console.error('purchase-flow:',(e as Error)?.message||e);return e instanceof AppError?json({error:e.message},e.status):json({error:'Satın alma işlemi tamamlanamadı.'},500)}})
