import GanuMark from '../GanuMark.jsx'
import { withBase } from '../base.js'
import LegalLinks from './LegalLinks.jsx'
import { legalIdentity } from './config.js'
import { POS_RETURN_STORAGE_KEY } from '../site/storageInventory.js'

const sources={
  distance:[['T.C. Ticaret Bakanlığı — Mesafeli Sözleşmeler Hakkında Bilgilendirme','https://tuketici.ticaret.gov.tr/yayinlar/tuketici-bilgi-rehberi/mesafeli-sozlesmeler-hakkinda-bilgilendirme']],
  privacy:[['KVKK — Aydınlatma Yükümlülüğü','https://www.kvkk.gov.tr/Icerik/2033/Aydinlatma-Yukumlulugu-'],['KVKK — Aydınlatma ve açık rızanın ayrı düzenlenmesi (2026/347)','https://www.kvkk.gov.tr/Icerik/8710/veri-sorumlulari-tarafindan-acik-riza-ve-aydinlatma-metinlerinin-ayri-ayri-duzenlenmesi-gerektigi-hakkinda-kisisel-verileri-koruma-kurulunun-18-02-2026-tarihli-ve-2026-347-sayili-ilke-kararina-iliskin-kamuoyu-duyurusu']],
  cookies:[['KVKK — Çerez Uygulamaları Hakkında Rehber','https://www.kvkk.gov.tr/Icerik/7353/Cerez-Uygulamalari-Hakkinda-Rehber']]
}
function Identity({locale}){
  if(!legalIdentity.complete)return <aside className="legal-draft" id="satis-kapali"><strong>{locale==='tr'?'Yayın öncesi hukuk incelemesi gerekiyor.':'Pre-publication legal review required.'}</strong><p>{locale==='tr'?'Satıcı/veri sorumlusu tescil bilgileri ve metin onay tarihi henüz doğrulanmadığı için bu taslak satış açmaz ve kimlik bilgisi yerine geçmez.':'The controller/provider identity and approval date have not yet been verified. This draft does not enable sales or represent a completed legal notice.'}</p></aside>
  return <dl className="legal-identity"><div><dt>{locale==='tr'?'Ticaret unvanı':'Legal name'}</dt><dd>{legalIdentity.tradeName}</dd></div><div><dt>{locale==='tr'?'Adres':'Address'}</dt><dd>{legalIdentity.address}</dd></div><div><dt>{locale==='tr'?'Vergi':'Tax registration'}</dt><dd>{legalIdentity.taxOffice} · {legalIdentity.taxNumber}</dd></div><div><dt>MERSİS / {locale==='tr'?'sicil':'registry'}</dt><dd>{legalIdentity.mersisNumber} · {legalIdentity.registryOffice} · {legalIdentity.registryNumber}</dd></div><div><dt>{locale==='tr'?'İletişim':'Contact'}</dt><dd><a href={`mailto:${legalIdentity.email}`}>{legalIdentity.email}</a> · {legalIdentity.phone}</dd></div><div><dt>{locale==='tr'?'Metin sürümü / onayı':'Text version / approval'}</dt><dd>{legalIdentity.textVersion} · {legalIdentity.approvedAt}</dd></div></dl>
}
function SourceList({items=[]}){return <section><h2>Resmî kaynaklar / Official sources</h2><ul>{items.map(([label,url])=><li key={url}><a href={url} rel="noreferrer">{label}</a></li>)}</ul></section>}
const trDistance=<>
  <h2>Kapsam ve taraflar</h2><p>{legalIdentity.complete?'Bu sayfa, bir tüketici ile uzaktan kurulacak sanal ofis hizmet sözleşmesinin ön bilgilendirmesidir.':'Bu sayfa, yalnız bir tüketici ile uzaktan kurulacak sanal ofis hizmet sözleşmesi için ön bilgilendirme taslağıdır.'} Ticari veya mesleki amaçla hareket eden şirket ve kişiler her işlemde “tüketici” sayılmayabilir; B2B hizmet sözleşmesinin koşulları ayrıca değerlendirilir.</p>
  <h2>Hizmet, bedel ve ifa</h2><p>Seçilen paket, toplam KDV dâhil bedel, ödeme yöntemi, sözleşme süresi ve hizmetin başlangıç şartları sipariş onayından hemen önce ayrıca gösterilmelidir. Adres kullanımının aktivasyonu; kimlik ve şirket belgelerinin kontrolü, sözleşmelerin imzası ve uygunluk incelemesi tamamlanmadan gerçekleşmez. Tescil, yoklama veya idari makam sonucu garanti edilmez.</p>
  <h2>Cayma hakkı</h2><p>Tüketici bakımından hizmet sözleşmesinde on dört günlük cayma süresi kural olarak sözleşmenin kurulduğu gün başlar. Bildirim, ispatlanabilir bir kalıcı veri saklayıcısı üzerinden sağlayıcıya yöneltilmelidir. Telefonla bildirim tek başına mevzuattaki yazılı/kalıcı veri saklayıcısı yönteminin yerine geçmeyebilir.</p>
  <h2>Erken ifa talebi ve istisna</h2><p>Cayma süresi dolmadan hizmete başlanması ancak tüketicinin açık ve önceden verilmiş talebi/onayı ile ele alınır. Bakanlık rehberi, tüketicinin onayıyla cayma süresi bitmeden ifasına başlanan hizmetleri cayma hakkı istisnaları arasında sayar. Sipariş akışı bu talebi bilgilendirme teyidinden ayrı kaydeder; ifade diğer yasal haklardan genel feragat değildir ve istisnanın uygulanması somut hizmete göre değerlendirilir.</p>
  <h2>Başvuru ve uyuşmazlık</h2><p>Cayma, iptal ve şikâyetler doğrulanmış kurumsal iletişim adresine gönderilir. Tüketicinin mevzuattan doğan tüketici hakem heyeti veya tüketici mahkemesi başvuru hakları saklıdır.</p>
  <h2>Mesafeli hizmet sözleşmesi hükümleri</h2><p>Sözleşme, tüketicinin ödeme öncesinde gösterilen paket, toplam bedel, süre, hizmet kapsamı ve bu metin sürümünü elektronik ortamda onaylamasıyla kurulur. Sağlayıcı yukarıdaki tescilli kimlikte belirtilen şirkettir; tüketici sipariş formundaki kişidir. Elektronik sipariş ve zaman damgalı kabul kaydı kalıcı veri saklayıcısı niteliğinde erişilebilir tutulur.</p><p>Sağlayıcı, yalnız sözleşmede sayılan adres kullanım belgesi, posta bildirimi ve seçili destek hizmetlerini uygunluk kontrolleri sonrasında sunar. Tüketici doğru belge ve iletişim bilgisi vermek, adresi hukuka uygun kullanmak ve kararlaştırılan bedeli ödemekle yükümlüdür. Yenileme, olağan fesih, yasaklı kullanım ve hizmet sınırları ödeme öncesi sipariş özetinde ve hizmet sözleşmesinde gösterilir; emredici tüketici hakları saklıdır.</p>
</>
const trReturns=<>
  <h2>Tüketici cayması</h2><p>Mesafeli hizmet sözleşmesinde tüketici, uygulanabilir bir istisna yoksa sözleşmenin kurulmasından itibaren on dört gün içinde gerekçe göstermeden cayma bildiriminde bulunabilir. Somut işlemin tüketici işlemi olup olmadığı ve hizmete başlanıp başlanmadığı ayrıca değerlendirilir.</p>
  <h2>İptal ve iade süreci</h2><p>Başvuru; siparişi belirlemeye yarayan bilgiyle, doğrulanmış kurumsal e-posta adresine kalıcı veri saklayıcısı üzerinden gönderilmelidir. Haklı ve süresinde cayma teyit edildiğinde iade, mevzuattaki yöntem ve süreler gözetilerek ilk ödeme aracıyla yapılır; banka/ödeme kuruluşu yansıma süresi ayrıca değişebilir.</p>
  <h2>Hizmet başladıysa</h2><p>Tüketicinin açık talebiyle cayma süresi içinde ifasına başlanmış hizmetlerde cayma istisnası gündeme gelebilir. Adres tahsisi, imzalı belge, posta işlemi veya başka bir edimin tamamlanma durumu somut olayda incelenir; bu açıklama peşinen cayma hakkından feragat oluşturmaz.</p>
  <h2>B2B fesih</h2><p>Ticari veya mesleki amaçla kurulan B2B sözleşmelerde tüketici cayma hükümleri yerine imzalanan hizmet sözleşmesinin süre, fesih ve ücret maddeleri uygulanabilir. Emredici hükümler saklıdır.</p>
</>
const trPrivacy=<>
  <h2>Aydınlatmanın kapsamı</h2><p>Bu taslak; web ziyareti, teklif/ortaklık başvurusu, satın alma adayı, müşteri portalı ve hizmet operasyonlarında işlenebilecek kimlik, iletişim, şirket, işlem, ödeme bildirimi, sözleşme ve teknik güvenlik verilerini açıklar. Kesin veri sorumlusu kimliği doğrulanmadan nihai aydınlatma sayılmaz.</p>
  <h2>Amaçlar ve hukuki sebepler</h2><p>Veriler; talebi yanıtlamak, sözleşme kurmak veya ifa etmek, fatura ve mevzuat yükümlülüklerini yerine getirmek, dolandırıcılığı önlemek, bilgi güvenliğini sağlamak ve hukuki talepleri yönetmek amaçlarıyla; KVKK’daki sözleşme, hukuki yükümlülük, hakkın tesisi/kullanılması ve meşru menfaat gibi somut işleme şartları ölçüsünde işlenir. Her faaliyet için ayrı hukuki sebep envanteri nihai metinde doğrulanmalıdır.</p>
  <h2>Aktarım ve saklama</h2><p>Gerekli veriler barındırma/altyapı, ödeme, e-fatura, iletişim ve yetkili kamu kurumlarıyla yalnız amaçla sınırlı ve uygun güvenceyle paylaşılabilir. Alıcı grupları, yurt dışı aktarım durumu ve saklama süreleri tedarikçi sözleşmeleri ile kayıt saklama yükümlülükleri doğrulandıktan sonra kesinleştirilmelidir.</p>
  <h2>Haklar ve başvuru</h2><p>İlgili kişiler KVKK madde 11 kapsamındaki hakları için, kimliği doğrulanmış veri sorumlusunun ilan edeceği başvuru kanalına müracaat edebilir. Aydınlatma yükümlülüğü açık rızadan ayrıdır; bu metni okumak veya siteyi kullanmak açık rıza verildiği anlamına gelmez.</p>
</>
const crossBorderTr={none:'Doğrulanmış veri akışı envanterine göre kişisel veriler yurt dışına aktarılmaz.',adequacy:'Yurt dışı aktarım yalnız KVKK madde 9 kapsamındaki yeterlilik kararı bulunan ülke/sektör/kuruluşlara ve amaçla sınırlı yapılır.','appropriate-safeguards':'Yurt dışı aktarım yalnız KVKK madde 9 kapsamındaki uygun güvence ve gerekli bildirim/izin süreçleriyle, amaçla sınırlı yapılır.'}
const crossBorderEn={none:'The verified data-flow inventory does not include an international transfer of personal data.',adequacy:'International transfers are limited to destinations covered by an adequacy decision under Article 9 of Law No. 6698 and to the stated purpose.','appropriate-safeguards':'International transfers are limited to the stated purpose and use an appropriate safeguard and any notification/authorisation required by Article 9 of Law No. 6698.'}
const trPrivacyFinal=<>
  <h2>Veri sorumlusu ve kapsam</h2><p>Yukarıdaki tescilli şirket, web ziyareti, teklif ve iş ortaklığı başvurusu, satın alma adayı, müşteri portalı ve hizmet operasyonları bakımından veri sorumlusudur. İşlenen gruplar; kimlik ve iletişim, şirket/vergi, işlem ve sözleşme, ödeme bildirimi, posta/hizmet kaydı ile secret-keyed HMAC ile takma adlandırılan IP ve kullanıcı aracısı gibi ölçülü teknik güvenlik verileridir. Bu değerler anonim değildir ve güvenlik değeri olarak korunur.</p>
  <h2>İşleme amaçları</h2><p>Veriler talepleri yanıtlamak, sözleşme öncesi adımları yürütmek, sözleşmeyi kurmak ve ifa etmek, fatura ve mevzuat yükümlülüklerini yerine getirmek, kötüye kullanımı önlemek, sistem güvenliğini sağlamak ve bir hakkı tesis, kullanmak veya korumak için işlenir.</p>
  <h2>Toplama yöntemi ve hukuki sebepler</h2><p>Veriler web formları, portal ve sözleşme işlemleri, ödeme kuruluşu bildirimleri, e-posta/telefon iletişimi ve güvenlik logları üzerinden otomatik veya kısmen otomatik yöntemlerle toplanır. Her faaliyet, niteliğine göre KVKK madde 5/2’deki sözleşmenin kurulması veya ifası, hukuki yükümlülük, bir hakkın tesisi/kullanılması/korunması ve ilgili kişinin temel haklarına zarar vermeyen meşru menfaat şartlarına dayanır. Zorunlu faaliyetler açık rıza ile birleştirilmez.</p>
  <h2>Alıcı grupları ve aktarım</h2><p>Gerekli veriler; barındırma ve bilgi güvenliği altyapısı, ödeme kuruluşu, e-fatura/muhasebe ve iletişim hizmet sağlayıcıları ile kanunen yetkili kamu kurumlarına, yalnız ilgili amaç ve asgari veriyle aktarılır. {crossBorderTr[legalIdentity.crossBorderStatus]}</p>
  <h2>Saklama</h2><p>Onaylı saklama politikası {legalIdentity.retentionVersion} uyarınca sonuçlanmayan talepler son temastan itibaren iki yıl; sözleşme, fatura ve temel ticari kayıtlar ilgili mali/ticari saklama yükümlülükleri gerektiriyorsa on yıl; güvenlik ve erişim kayıtları amaç için gerekli en kısa süre ve kural olarak bir yıl saklanır. Hukuki uyuşmazlık veya yetkili makam talebi varsa yalnız gerekli kayıt ilgili süre sonuna kadar korunur ve ardından silinir, yok edilir veya anonimleştirilir.</p>
  <h2>KVKK madde 11 hakları ve başvuru</h2><p>İlgili kişiler verilerinin işlenip işlenmediğini öğrenme, bilgi talep etme, amaca uygun kullanımı öğrenme, aktarılan kişileri bilme, düzeltme, silme/yok etme isteme, düzeltme veya silmenin alıcılara bildirilmesini isteme, otomatik analiz sonucuna itiraz ve kanuna aykırı işleme nedeniyle zararın giderilmesini talep haklarını kullanabilir. Başvuru, kimliği doğrulamaya elverişli bilgiyle <a href={`mailto:${legalIdentity.email}`}>{legalIdentity.email}</a> kanalına veya yukarıdaki veri sorumlusu adresine yöneltilebilir. Aydınlatma açık rızadan ayrıdır.</p>
</>
const trCookies=<>
  <h2>Fiilî teknoloji envanteri</h2><p>Public pazarlama sayfalarında şu anda reklam veya davranışsal analiz çerezi kurulmamaktadır ve kod tabanında Google Analytics, Meta Pixel ya da benzeri bir izleyici bulunmamaktadır. Bu nedenle yalnız “çerez kabulü” isteyen bir banner gösterilmez.</p>
  <h2>Supabase oturumu</h2><p>Personel ve müşteri portallarında Supabase Auth, güvenli oturumu sürdürebilmek için tarayıcı depolamasında oturum bilgisi kullanabilir. Kullanılan anahtar adı Supabase istemci sürümü ve proje adresine göre değişebilir. Bu veri giriş ve yetkilendirme işlevi içindir; pazarlama profili oluşturmak için kullanılmaz.</p>
  <h2>Uygulama depolaması</h2><p>Ödeme sağlayıcısı dönüşündeki tek kullanımlık <code>{POS_RETURN_STORAGE_KEY}</code> kaydı, doğrudan kimlik alanı taşımayan fakat siparişle ilişkilendirilebilir opak/pseudonymous bir güvenlik değeridir; hassas korunur, <code>sessionStorage</code> içinde en fazla bir saat tutulur ve terminal durumda silinir. <code>ganu.panel.*</code> kayıtları yalnız yerel geliştirme/demo içindir. <code>ganu.musteri.session</code> ve <code>ganu.ortak.session</code> eski erişim-kodu yüzeyleridir; production kimlik doğrulamasının hukuki dayanağı olarak görülmez ve cloud cutover’da kapalı/fail-closed kalmalıdır.</p>
  <h2>Gelecekte tercih yönetimi</h2><p>Analitik veya reklam teknolojisi eklenirse, zorunlu olmayan depolama varsayılan olarak kapalı tutulmalı; eşit görünür “Kabul”, “Reddet” ve “Tercihler” seçenekleriyle önceden opt-in alınmalı ve bu envanter güncellenmelidir.</p>
</>
const enPrivacy=<><h2>Scope</h2><p>This draft covers website visits, quote and partnership enquiries, purchase candidates, customer-portal access and service operations. Data may include identity/contact, company, transaction, contract, receipt and technical-security records. It is not a final controller notice until the legal identity above is verified.</p><h2>Purposes and legal grounds</h2><p>Data is used only as necessary to answer enquiries, take pre-contract steps, perform a contract, meet invoicing/legal duties, prevent abuse, secure systems and establish or defend legal claims. The final notice must map each activity to a specific condition under Turkish Law No. 6698.</p><h2>Recipients and retention</h2><p>Necessary data may be disclosed on a limited basis to hosting/infrastructure, payment, invoicing and communication providers or competent authorities. Recipient groups, international transfers and retention periods must be confirmed against actual vendor contracts and statutory records before launch.</p><h2>Your rights</h2><p>Data subjects may exercise the rights under Article 11 through the verified controller channel. This notice is separate from consent: reading it, submitting a necessary service enquiry or using the site is not blanket consent for optional processing.</p></>
const enPrivacyFinal=<><h2>Controller and scope</h2><p>The registered company identified above is the controller for website visits, quote and partnership enquiries, purchase candidates, customer-portal access and service operations. Categories include identity/contact, company/tax, transaction/contract, payment notice, mail/service and proportionate technical-security data such as IP and user-agent hashes.</p><h2>Purposes</h2><p>Data is processed to answer requests, take pre-contract steps, enter into and perform the agreement, meet invoicing and statutory duties, prevent abuse, secure systems and establish, exercise or defend legal claims.</p><h2>Collection method and legal grounds</h2><p>Data is collected automatically or partly automatically through web forms, portal/contract actions, payment-provider notices, email/phone contact and security logs. Depending on the activity, processing relies on Article 5/2 conditions for entering into or performing a contract, legal obligation, establishment/exercise/protection of a right, and legitimate interests that do not prejudice fundamental rights. Required processing is not bundled with consent.</p><h2>Recipient groups and transfers</h2><p>Only necessary data is disclosed to hosting and security infrastructure, payment, e-invoicing/accounting and communication providers, and competent public authorities, limited to the relevant purpose. {crossBorderEn[legalIdentity.crossBorderStatus]}</p><h2>Retention</h2><p>Under approved retention schedule {legalIdentity.retentionVersion}, unsuccessful enquiries are retained for two years after the last contact; contracts, invoices and core commercial records are retained for ten years where applicable statutory duties require it; security/access records are retained for the shortest necessary period and normally one year. Records subject to a legal dispute or authority request are restricted until the relevant period ends, then deleted, destroyed or anonymised.</p><h2>Article 11 rights and channel</h2><p>Data subjects may exercise the Article 11 rights to information, access, correction, deletion/destruction, recipient notification, objection to an exclusively automated adverse result and compensation for unlawful processing. A request with sufficient identity-verification information may be sent to <a href={`mailto:${legalIdentity.email}`}>{legalIdentity.email}</a> or the controller address above. This notice remains separate from consent.</p></>
const enCookies=<><h2>Current inventory</h2><p>The public marketing pages do not currently install advertising or behavioural-analytics cookies. The codebase contains no Google Analytics, Meta Pixel or equivalent tracker, so the site does not display a misleading consent banner. Cookies and browser-storage technologies are described separately here.</p><h2>Authentication storage</h2><p>Supabase Auth may use browser storage in staff and customer portals to maintain a secure authenticated session; the exact key can vary by client version and project URL. It is used for login and authorisation, not advertising profiles.</p><h2>Application storage</h2><p>The single-use <code>{POS_RETURN_STORAGE_KEY}</code> record contains no direct identity field, but is an opaque/pseudonymous security value that can be linked to an order. It is treated as sensitive, kept in <code>sessionStorage</code> for at most one hour and removed on a terminal result. <code>ganu.panel.*</code> is local-development/demo state. <code>ganu.musteri.session</code> and <code>ganu.ortak.session</code> are legacy access-code surfaces; they are not a legitimate production authentication basis and must remain disabled/fail-closed after cloud cutover.</p><h2>Future optional technologies</h2><p>If analytics or advertising is introduced, non-essential storage must remain off until an equal, prior choice to Accept, Reject or manage Preferences is provided, and this inventory must be updated.</p></>

export default function LegalPage({type,locale='tr'}){
  const approved=legalIdentity.complete
  const body={distance:trDistance,returns:trReturns,privacy:locale==='tr'?(approved?trPrivacyFinal:trPrivacy):(approved?enPrivacyFinal:enPrivacy),cookies:locale==='tr'?trCookies:enCookies}[type]
  const baseTitle={distance:'Mesafeli Satış Ön Bilgilendirmesi ve Sözleşme',returns:'İptal, Cayma ve İade',privacy:locale==='tr'?'KVKK Aydınlatma Metni':'Privacy Notice',cookies:locale==='tr'?'Çerez ve Tarayıcı Depolama Bildirimi':'Cookies and Browser Storage Notice'}[type]
  const title=approved?baseTitle:`${baseTitle}${locale==='tr'?' Taslağı':' Draft'}`
  const counterpart=type==='privacy'?(locale==='tr'?'/en/privacy':'/kvkk'):type==='cookies'?(locale==='tr'?'/en/cookies':'/cerezler'):''
  const kicker=approved?(locale==='tr'?`YASAL BİLGİLENDİRME · SÜRÜM ${legalIdentity.textVersion}`:`LEGAL NOTICE · VERSION ${legalIdentity.textVersion}`):(locale==='tr'?'HUKUKİ TASLAK · NİHAİ AVUKAT ONAYI GEREKİR':'LEGAL DRAFT · FINAL COUNSEL APPROVAL REQUIRED')
  const disclaimer=approved?(locale==='tr'?'Bu metin, belirtilen sürüm ve onay tarihiyle yayımlanan genel bilgilendirmedir; somut olay için hukuki danışmanlık değildir.':'This is the published general notice for the stated version and approval date; it is not advice for a specific matter.'):(locale==='tr'?'Bu metin genel bilgilendirme ve lansman hazırlığı içindir; hukuki danışmanlık değildir. Kimlik, tedarikçi, saklama ve satış akışı gerçek durumla eşleştirilip avukatça onaylanmadan üretimde satış açılamaz.':'This text supports pre-launch review and is not legal advice. Production sales must remain disabled until identity, vendors, retention and the actual flow are verified and approved by Turkish counsel.')
  const evidenceNote=approved&&type==='privacy'&&locale==='en'?<p>IP and user-agent evidence is pseudonymised with domain-separated, secret-keyed HMAC-SHA-256. It is not anonymous data and remains protected as a security value.</p>:null
  return <div className="legal-shell"><header className="legal-mast"><a href={withBase(locale==='tr'?'/':'/en')} aria-label="GANU"><GanuMark/></a><LegalLinks locale={locale} compact/>{counterpart&&<a className="lang-switch" href={withBase(counterpart)}>{locale==='tr'?'EN':'TR'}</a>}</header><main><article className="legal-page"><p className="legal-kicker">{kicker}</p><h1>{title}</h1><p className="legal-updated">{locale==='tr'?(approved?'Onay tarihi':'Taslak güncelleme'):(approved?'Approved':'Draft updated')}: {approved?legalIdentity.approvedAt:'15.08.2026'}</p><Identity locale={locale}/>{evidenceNote}{body}<SourceList items={sources[type]||sources[type==='returns'?'distance':type]}/><aside className="legal-disclaimer">{disclaimer}</aside></article></main><footer className="legal-footer"><span>© {new Date().getFullYear()} GANU</span><LegalLinks locale={locale} compact/></footer></div>
}
