import { useEffect,useState } from 'react'
import { Navigate,NavLink,Route,Routes,useNavigate } from 'react-router-dom'
import GanuMark from '../GanuMark.jsx'
import { withBase } from '../base.js'
import { authMode,getUser,login,logout,onAuthChange,sendMagicLink } from './lib/operations-auth.js'
import OperationsOverview from './pages/OperationsOverview.jsx'
import Kargo from './pages/Kargo.jsx'
import Sozlesmeler from './pages/Sozlesmeler.jsx'
import OperationsCustomers from './pages/OperationsCustomers.jsx'
import OperationsCustomerDetail from './pages/OperationsCustomerDetail.jsx'
import ToplantiOdasi from './pages/ToplantiOdasi.jsx'
import Yoklama from './pages/Yoklama.jsx'
import OperationsRecords from './pages/OperationsRecords.jsx'
import OperationsSettings from './pages/OperationsSettings.jsx'
import './panel.css'

const navItems=[['/panel','Operasyon',true],['/panel/musteriler','Müşteriler'],['/panel/kargo','Kargo, Posta & Tebligat'],['/panel/sozlesmeler','Sözleşmeler'],['/panel/belgeler','Belgeler'],['/panel/talepler','Talepler'],['/panel/toplanti-odasi','Toplantı Odası'],['/panel/yoklama','Yoklama'],['/panel/faturalar','Faturalar & Gelir'],['/panel/masraflar','Masraflar'],['/panel/ortaklar','İş Ortakları & Komisyon'],['/panel/bildirimler','Bildirimler'],['/panel/ayarlar','Ayarlar & Raporlar']]

function Login({onOk}){const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[note,setNote]=useState('');const submit=async(e)=>{e.preventDefault();setBusy(true);setError('');const result=await login({email,password});setBusy(false);if(result.ok)onOk();else{setError(result.error);setPassword('')}};const magic=async()=>{if(!email.trim()){setError('Önce e-posta adresinizi yazın');return}setBusy(true);setError('');const result=await sendMagicLink(email);setBusy(false);result.ok?setNote('Güvenli giriş bağlantısı e-postanıza gönderildi.'):setError(result.error)};return <main className="pl-login"><form className="pl-login-card" onSubmit={submit} data-staff-auth="supabase-rbac"><div className="pl-login-mark"><GanuMark/></div><h1>Personel Girişi <small>Beta</small></h1><p>Yalnız yetkili GANU personeli · staging backend</p>{authMode==='disabled'&&<span className="pl-login-err">Personel girişi yapılandırılmadı.</span>}<label htmlFor="staff-email">E-posta</label><input id="staff-email" type="email" autoComplete="username" value={email} onChange={(e)=>setEmail(e.target.value)} placeholder="info@ganu.com.tr" required/><label htmlFor="staff-password">Parola (varsa)</label><input id="staff-password" type="password" autoComplete="current-password" value={password} onChange={(e)=>setPassword(e.target.value)}/>{error&&<span className="pl-login-err" role="alert">{error}</span>}{note&&<span className="pl-login-ok">{note}</span>}<button className="pl-btn pl-btn-solid" disabled={busy||authMode==='disabled'}>{busy?'Giriş yapılıyor…':'Parola ile giriş →'}</button><button type="button" className="pl-linkbtn" disabled={busy||authMode==='disabled'} onClick={magic}>E-posta ile güvenli giriş bağlantısı</button></form></main>}

function Shell({children}){const [open,setOpen]=useState(false),navigate=useNavigate();const signOut=async()=>{await logout();navigate('/panel',{replace:true})};return <div className="pl-shell"><aside className={`pl-side${open?' open':''}`}><a href={withBase('/')} className="pl-brand"><GanuMark/><span>operasyon</span></a><nav className="pl-nav">{navItems.map(([to,label,end])=><NavLink key={to} to={to} end={!!end} className="pl-nav-link" onClick={()=>setOpen(false)}>{label}</NavLink>)}</nav><button className="pl-logout" onClick={signOut}>Çıkış yap</button></aside>{open&&<button className="pl-overlay" aria-label="Menüyü kapat" onClick={()=>setOpen(false)}/>}<div className="pl-main"><header className="pl-topbar"><button className="pl-burger" aria-label="Menü" onClick={()=>setOpen((v)=>!v)}>☰</button><a href={withBase('/')} className="pl-back">← Siteye dön</a></header><div className="pl-content">{children}</div></div></div>}

export default function OperationsPanelApp(){const [user,setUser]=useState(null),[checking,setChecking]=useState(true);useEffect(()=>{document.title='GANU · Personel Girişi';let live=true;getUser().then((value)=>{if(live)setUser(value)}).finally(()=>{if(live)setChecking(false)});const unsubscribe=onAuthChange((value)=>{if(live){setUser(value);setChecking(false)}});return()=>{live=false;unsubscribe()}},[]);if(checking)return <main className="pl-login" aria-busy="true"><div className="pl-login-card"><h1>Personel Girişi</h1><p>Yetkili oturum denetleniyor. Bu sayfa giriş yapılmadan şirket verisi göstermez.</p></div></main>;if(!user)return <Login onOk={()=>getUser().then(setUser)}/>;return <Shell><Routes><Route index element={<OperationsOverview/>}/><Route path="kargo" element={<Kargo/>}/><Route path="musteriler" element={<OperationsCustomers/>}/><Route path="musteriler/:id" element={<OperationsCustomerDetail/>}/><Route path="sozlesmeler" element={<Sozlesmeler/>}/><Route path="belgeler" element={<OperationsRecords kind="belgeler"/>}/><Route path="talepler" element={<OperationsRecords kind="talepler"/>}/><Route path="toplanti-odasi" element={<ToplantiOdasi/>}/><Route path="yoklama" element={<Yoklama/>}/><Route path="faturalar" element={<OperationsRecords kind="faturalar"/>}/><Route path="masraflar" element={<OperationsRecords kind="masraflar"/>}/><Route path="ortaklar" element={<OperationsRecords kind="ortaklar"/>}/><Route path="bildirimler" element={<OperationsRecords kind="bildirimler"/>}/><Route path="ayarlar" element={<OperationsSettings/>}/><Route path="*" element={<Navigate to="/panel" replace/>}/></Routes></Shell>}
