import { useEffect,useState } from 'react'
import { Link,useParams } from 'react-router-dom'
import { customers,contracts,mail,documents,requests,inspections,invoices,partners,DOC_TYPES,REQUEST_STATUS,fileToStoredUrl } from '../lib/operations-store.js'
import { SecureLink } from '../components/SecureAsset.jsx'
import { fmtDate,fmtTL } from './_ui.jsx'
import CustomerForm,{ customerPayload,missingForInvoice,validateCustomer } from './OperationsCustomerForm.jsx'
import { CustomerBadge } from './OperationsCustomers.jsx'
import { EDocCell,InvoiceBadge,InvoiceForm,PaymentLinkButton,PaymentMessageButton,ReviewNote,emptyInvoice,markPaid } from './OperationsInvoices.jsx'
export default function OperationsCustomerDetail(){
  const {id}=useParams(),[customer,setCustomer]=useState(null),[data,setData]=useState(null),[busy,setBusy]=useState(false),[docType,setDocType]=useState('sozlesme'),[modal,setModal]=useState(null)
  const load=async()=>{const c=await customers.get(id);setCustomer(c);if(!c){setData({contracts:[],mail:[],documents:[],requests:[],inspections:[],invoices:[],all:[],partners:[]});return}const [ct,ml,docs,req,ins,inv,all,ps]=await Promise.all([contracts.list(),mail.list(),documents.list(),requests.list(),inspections.list(),invoices.list(),customers.list(),partners.list()]);const mine=(x)=>x.customer_id===id;setData({contracts:ct.filter(mine),mail:ml.filter(mine),documents:docs.filter(mine),requests:req.filter(mine),inspections:ins.filter(mine),invoices:inv.filter(mine),all,partners:ps})}
  useEffect(()=>{load()},[id])
  const upload=async(e)=>{const file=e.target.files?.[0];if(!file)return;setBusy(true);try{const stored=await fileToStoredUrl(file,{prefix:'customers',customerId:id});await documents.create({customer_id:id,name:file.name,type:docType,file_url:stored,note:'Personel panelinden yüklendi'});await load()}finally{setBusy(false);e.target.value=''}}
  const saveCustomer=async(form)=>{const msg=validateCustomer(form,data.all,id);if(msg)return msg;await customers.update(id,customerPayload(form));setModal(null);await load()}
  const saveInvoice=async(payload)=>{if(modal.mode==='new')await invoices.create(payload);else await invoices.update(modal.data.id,payload);setModal(null);await load()}
  if(!data)return <div className="pl-empty">Yükleniyor…</div>
  if(!customer)return <div className="pl-empty">Müşteri bulunamadı. <Link to="/panel/musteriler">Listeye dön</Link></div>
  const missing=missingForInvoice(customer),partner=data.partners.find((p)=>p.id===customer.partner_id)
  return <div><div className="pl-head"><div><div className="pl-crumb"><Link to="/panel/musteriler">← Müşteriler</Link></div><h1>{customer.title} <CustomerBadge s={customer.status}/></h1><p>{customer.contact||'—'}{customer.bni?' · BNI Nişantaşı':''}{partner?` · ortak: ${partner.name}`:''}</p></div><button className="pl-btn pl-btn-ghost" onClick={()=>setModal({kind:'customer'})}>Düzenle</button></div>
    {missing.length>0&&<div className="pl-alert"><span className="ic">!</span><span className="msg">Fatura kesmeden önce eksik: <b>{missing.join(', ')}</b>.</span></div>}
    <div className="pl-card"><div className="pl-card-b"><div className="pl-kv"><div><span className="k">E-posta</span><span className="v">{customer.email||'—'}</span></div><div><span className="k">Telefon</span><span className="v">{customer.phone||'—'}</span></div><div><span className="k">Vergi dairesi/no</span><span className="v">{customer.tax_office||'—'} · {customer.tax_no||customer.tc||'—'}</span></div><div><span className="k">Adres</span><span className="v">{[customer.address,customer.district,customer.city].filter(Boolean).join(', ')||'—'}</span></div>{customer.notes&&<div><span className="k">Not</span><span className="v">{customer.notes}</span></div>}</div></div></div>
    <div className="pl-card" style={{marginTop:20}}><div className="pl-card-h"><h2>Sözleşmeler</h2><Link className="pl-btn pl-btn-ghost pl-btn-sm" to={`/panel/sozlesmeler?musteri=${id}`}>+ Sözleşme</Link></div><div className="pl-card-b">{data.contracts.length===0&&<div className="pl-empty">Kayıt yok.</div>}{data.contracts.map((x)=><div className="pl-row" key={x.id}><div className="grow"><b>{x.package}</b> · {fmtDate(x.start_date)}–{fmtDate(x.end_date)} · {fmtTL(x.price)} /{x.billing_period==='aylık'?'ay':'yıl'} · {x.status}</div></div>)}</div></div>
    <div className="pl-card" style={{marginTop:20}}><div className="pl-card-h"><h2>Faturalar</h2><button className="pl-btn pl-btn-ghost pl-btn-sm" onClick={()=>setModal({kind:'invoice',mode:'new',data:emptyInvoice(id)})}>+ Fatura kaydı</button></div><div className="pl-card-b">{data.invoices.length===0&&<div className="pl-empty">Kayıt yok.</div>}{data.invoices.map((x)=><div className="pl-row" key={x.id}><div className="grow"><div className="t1">{fmtTL(x.amount)} <InvoiceBadge row={x}/></div><div className="t2">{fmtDate(x.issue_date)} · son ödeme {fmtDate(x.due_date)}{x.note?` · ${x.note}`:''}{x.payment_link&&x.status!=='ödendi'?' · kart linki eklendi':''}</div><div className="t2"><EDocCell row={x} onDone={load}/></div><ReviewNote row={x}/></div><div className="pl-actions">{x.status!=='ödendi'&&<><PaymentLinkButton row={x} onDone={load}/><PaymentMessageButton row={x} customer={customer}/><button className="pl-btn pl-btn-teal pl-btn-sm" onClick={async()=>{await markPaid(x);load()}}>Ödendi</button></>}<button className="pl-btn pl-btn-ghost pl-btn-sm" onClick={()=>setModal({kind:'invoice',mode:'edit',data:{...x}})}>Düzenle</button></div></div>)}</div></div>
    <Section title="Kargo & Posta" rows={data.mail} render={(x)=><>{x.type} · {x.sender||'—'} · {fmtDate(x.received_date)} · {x.status}</>}/>
    <div className="pl-card" style={{marginTop:20}}><div className="pl-card-h"><h2>Evraklar</h2><div className="pl-actions"><select value={docType} onChange={(e)=>setDocType(e.target.value)} aria-label="Evrak türü">{DOC_TYPES.map((d)=><option key={d.v} value={d.v}>{d.l}</option>)}</select><label className="pl-btn pl-btn-ghost pl-btn-sm">{busy?'Yükleniyor…':'Evrak yükle'}<input hidden type="file" accept="image/*,application/pdf" disabled={busy} onChange={upload}/></label></div></div><div className="pl-card-b">{data.documents.length===0&&<div className="pl-empty">Evrak yok.</div>}{data.documents.map((x)=><div className="pl-row" key={x.id}><div className="grow"><div className="t1">{x.name}</div><div className="t2">{DOC_TYPES.find((d)=>d.v===x.type)?.l||x.type} · {fmtDate(x.created_at)}</div></div><SecureLink stored={x.file_url} target="_blank" rel="noreferrer">Aç ↗</SecureLink></div>)}</div></div>
    <div className="pl-card" style={{marginTop:20}}><div className="pl-card-h"><h2>Talepler</h2></div><div className="pl-card-b">{data.requests.length===0&&<div className="pl-empty">Talep yok.</div>}{data.requests.map((x)=><div className="pl-row" key={x.id}><div className="grow"><div className="t1">{x.kind}</div><div className="t2">{x.note||'—'} · {fmtDate(x.created_at)}</div></div><select value={x.status} onChange={async(e)=>{await requests.update(x.id,{status:e.target.value});load()}}>{REQUEST_STATUS.map((s)=><option key={s}>{s}</option>)}</select></div>)}</div></div>
    <Section title="Yoklama" rows={data.inspections} render={(x)=><>{fmtDate(x.date)} · {x.result} · {x.note||'—'}</>}/>
    {modal?.kind==='customer'&&<CustomerForm title="Müşteriyi düzenle" initial={customer} partners={data.partners} onClose={()=>setModal(null)} onSave={saveCustomer}/>}
    {modal?.kind==='invoice'&&<InvoiceForm title={modal.mode==='new'?'Yeni fatura kaydı':'Fatura kaydını düzenle'} initial={modal.data} custs={[customer]} cts={data.contracts} lockCustomer onClose={()=>setModal(null)} onSave={saveInvoice}/>}
  </div>
}
function Section({title,rows,render}){return <div className="pl-card" style={{marginTop:20}}><div className="pl-card-h"><h2>{title}</h2></div><div className="pl-card-b">{rows.length===0&&<div className="pl-empty">Kayıt yok.</div>}{rows.map((x)=><div className="pl-row" key={x.id}><div className="grow">{render(x)}</div></div>)}</div></div>}
