import { useEffect,useState } from 'react'
import { Link,useParams,useSearchParams } from 'react-router-dom'
import { customers,contracts,mail,documents,requests,inspections,invoices,partners,invStatus,setMailStatus,DOC_TYPES,MAIL_STATUS,REQUEST_STATUS,fileToStoredUrl } from '../lib/operations-store.js'
import { SecureLink } from '../components/SecureAsset.jsx'
import { fmtDate,fmtTL } from './_ui.jsx'
import { daysUntil,oneYearLaterISO } from '../lib/dates.js'
import CustomerForm,{ customerPayload,missingForInvoice,validateCustomer } from './OperationsCustomerForm.jsx'
import { CustomerBadge } from './OperationsCustomers.jsx'
import { EDocCell,InvoiceBadge,InvoiceForm,PaymentLinkButton,PaymentMessageButton,ReviewNote,emptyInvoice,markPaid,paidSource } from './OperationsInvoices.jsx'
export default function OperationsCustomerDetail(){
  const {id}=useParams(),[params,setParams]=useSearchParams(),[customer,setCustomer]=useState(null),[data,setData]=useState(null),[busy,setBusy]=useState(false),[docType,setDocType]=useState('sozlesme'),[modal,setModal]=useState(null)
  const load=async()=>{const c=await customers.get(id);setCustomer(c);if(!c){setData({contracts:[],mail:[],documents:[],requests:[],inspections:[],invoices:[],all:[],partners:[]});return}const [ct,ml,docs,req,ins,inv,all,ps]=await Promise.all([contracts.list(),mail.list(),documents.list(),requests.list(),inspections.list(),invoices.list(),customers.list(),partners.list()]);const mine=(x)=>x.customer_id===id;setData({contracts:ct.filter(mine),mail:ml.filter(mine),documents:docs.filter(mine),requests:req.filter(mine),inspections:ins.filter(mine),invoices:inv.filter(mine),all,partners:ps})}
  useEffect(()=>{load()},[id])
  const upload=async(e)=>{const file=e.target.files?.[0];if(!file)return;setBusy(true);try{const stored=await fileToStoredUrl(file,{prefix:'customers',customerId:id});await documents.create({customer_id:id,name:file.name,type:docType,file_url:stored,note:'Personel panelinden yüklendi'});await load()}finally{setBusy(false);e.target.value=''}}
  const saveCustomer=async(form)=>{const msg=validateCustomer(form,data.all,id);if(msg)return msg;await customers.update(id,customerPayload(form));setModal(null);await load()}
  const saveInvoice=async(payload)=>{if(modal.mode==='new')await invoices.create(payload);else await invoices.update(modal.data.id,payload);setModal(null);await load()}
  if(!data)return <div className="pl-empty">Yükleniyor…</div>
  if(!customer)return <div className="pl-empty">Müşteri bulunamadı. <Link to="/panel/musteriler">Listeye dön</Link></div>
  const missing=missingForInvoice(customer),partner=data.partners.find((p)=>p.id===customer.partner_id),signed=data.documents.some((d)=>d.type==='sozlesme')
  const openInv=data.invoices.filter((x)=>invStatus(x)!=='ödendi'),lateInv=openInv.filter((x)=>invStatus(x)==='gecikti'),lastContract=[...data.contracts].sort((a,b)=>String(b.end_date||'').localeCompare(String(a.end_date||'')))[0]
  const lastIns=[...data.inspections].sort((a,b)=>String(b.date||'').localeCompare(String(a.date||'')))[0],openReq=data.requests.filter((x)=>!['tamamlandı','reddedildi'].includes(x.status))
  // İş bekleyenler: teslim/yönlendirme/imha edilmemiş posta, sonucu beklenen yoklama.
  const openMail=data.mail.filter((x)=>['geldi','bildirildi'].includes(x.status)),openTeb=openMail.filter((x)=>x.type==='tebligat'),openIns=data.inspections.filter((x)=>x.result==='bekleniyor')
  // Bekleyen tebligat en üstte: hukuki süreler tebligatla başlar.
  const isOpenTebligat=(x)=>x.type==='tebligat'&&['geldi','bildirildi'].includes(x.status),mailSorted=[...data.mail].sort((a,b)=>Number(isOpenTebligat(b))-Number(isOpenTebligat(a)))
  const daysLeft=lastContract?.end_date?daysUntil(lastContract.end_date):null
  const mailStatus=async(x,v)=>{await setMailStatus(x,v,customer);load()}
  const insResult=async(x,v)=>{await inspections.update(x.id,{result:v});load()}
  const renew=async(x)=>{if(!confirm(`${x.package} sözleşmesi ${fmtDate(x.end_date)} tarihinden itibaren 1 yıl yenilensin mi?`))return;await contracts.update(x.id,{start_date:x.end_date,end_date:oneYearLaterISO(x.end_date),status:'aktif'});load()}
  // Sanal ofis operasyon önceliği: posta/talep/yoklama önde. Sayı = iş bekleyen kayıt (toplam değil).
  // Başlangıç kontrol listesi: yeni müşterinin evrak ve ilk tahsilat adımları; eksikse ilgili sekme açılır.
  const hasDoc=(t)=>data.documents.some((d)=>d.type===t)
  const steps=[['Kimlik ve vergi bilgileri tam',missing.length===0,null],['Vergi levhası yüklendi',hasDoc('vergi_levhasi'),'belgeler','vergi_levhasi'],['İmza sirküleri / kimlik yüklendi',hasDoc('imza_sirkuleri')||hasDoc('kimlik'),'belgeler','imza_sirkuleri'],['Hizmet sözleşmesi imzalı yüklendi',signed,'belgeler','sozlesme'],['Adres kullanım (muvafakat) belgesi yüklendi',hasDoc('isyeri_kullanim'),'belgeler','isyeri_kullanim'],['Sözleşme kaydı (paket, süre) girildi',data.contracts.length>0,'sozlesmeler'],['İlk ödeme alındı',data.invoices.some((x)=>invStatus(x)==='ödendi'),'faturalar'],['e-Fatura/e-Arşiv kesildi',data.invoices.some((x)=>x.einvoice_status==='kesildi'||x.einvoice_no),'faturalar']]
  const doneSteps=steps.filter(([,ok])=>ok).length
  const tabs=[['ozet','Özet'],['posta','Posta & Kargo',openMail.length],['talepler','Talepler',openReq.length],['yoklama','Yoklama',openIns.length],['sozlesmeler','Sözleşmeler'],['faturalar','Faturalar',openInv.length],['belgeler','Belgeler']]
  const tab=tabs.some(([k])=>k===params.get('sekme'))?params.get('sekme'):'ozet'
  const go=(k)=>setParams(k==='ozet'?{}:{sekme:k},{replace:true})
  const onTabKey=(e)=>{const i=tabs.findIndex(([k])=>k===tab),d=e.key==='ArrowRight'?1:e.key==='ArrowLeft'?-1:0;if(!d)return;e.preventDefault();const k=tabs[(i+d+tabs.length)%tabs.length][0];go(k);document.getElementById(`tab-${k}`)?.focus()}
  return <div><div className="pl-head"><div><div className="pl-crumb"><Link to="/panel/musteriler">← Müşteriler</Link></div><h1>{customer.title} <CustomerBadge s={customer.status}/></h1><p>{customer.contact||'—'}{customer.bni?' · BNI Nişantaşı':''}{partner?` · ortak: ${partner.name}`:''}</p></div><button className="pl-btn pl-btn-ghost" onClick={()=>setModal({kind:'customer'})}>Düzenle</button></div>
    {!signed&&<div className="pl-alert"><span className="ic">✍</span><span className="msg">İmzalı hizmet sözleşmesi yüklenmedi — <button type="button" className="pl-linkbtn" onClick={()=>{setDocType('sozlesme');go('belgeler')}}>Belgeler</button> sekmesinden türü <b>Sözleşme</b> seçerek yükleyin.</span></div>}
    {missing.length>0&&<div className="pl-alert"><span className="ic">!</span><span className="msg">Fatura kesmeden önce eksik: <b>{missing.join(', ')}</b>.</span></div>}
    <div className="pl-tabs" role="tablist" aria-label="Müşteri bölümleri" onKeyDown={onTabKey}>{tabs.map(([k,l,n])=><button key={k} id={`tab-${k}`} type="button" role="tab" className="pl-tab" aria-selected={tab===k} aria-controls={`panel-${k}`} tabIndex={tab===k?0:-1} onClick={()=>go(k)}>{l}{n>0&&<span className="n hot" aria-label={`${n} iş bekliyor`}>{n}</span>}</button>)}</div>
    <div role="tabpanel" id={`panel-${tab}`} aria-labelledby={`tab-${tab}`}>
    {tab==='ozet'&&<><div className="pl-card"><div className="pl-card-b"><div className="pl-kv"><div><span className="k">E-posta</span><span className="v">{customer.email||'—'}</span></div><div><span className="k">Telefon</span><span className="v">{customer.phone||'—'}</span></div><div><span className="k">Vergi dairesi/no</span><span className="v">{customer.tax_office||'—'} · {customer.tax_no||customer.tc||'—'}</span></div><div><span className="k">Adres</span><span className="v">{[customer.address,customer.district,customer.city].filter(Boolean).join(', ')||'—'}</span></div>{customer.notes&&<div><span className="k">Not</span><span className="v">{customer.notes}</span></div>}</div></div></div>
      <div className="pl-facts">
        <button type="button" className="pl-fact" onClick={()=>go('sozlesmeler')}><div className="lab">Sözleşme</div><div className="val">{lastContract?`${lastContract.package} · ${lastContract.status}`:'Yok'}</div>{daysLeft!==null&&<div className={`sub${daysLeft<=30?' warn':''}`}>{daysLeft>=0?`bitişe ${daysLeft} gün · ${fmtDate(lastContract.end_date)}`:`${-daysLeft} gün önce bitti`}</div>}</button>
        <button type="button" className="pl-fact" onClick={()=>go('faturalar')}><div className="lab">Ödenmemiş fatura</div><div className="val">{openInv.length?`${openInv.length} · ${fmtTL(openInv.reduce((n,x)=>n+(Number(x.amount)||0),0))}`:'Yok'}</div>{lateInv.length>0&&<div className="sub warn">{lateInv.length} gecikmiş</div>}</button>
        <button type="button" className="pl-fact" onClick={()=>go('posta')}><div className="lab">Bekleyen posta</div><div className="val">{openMail.length||'Yok'}</div>{openTeb.length>0&&<div className="sub warn">{openTeb.length} tebligat</div>}</button>
        <button type="button" className="pl-fact" onClick={()=>go('yoklama')}><div className="lab">Son yoklama</div><div className="val">{lastIns?`${fmtDate(lastIns.date)} · ${lastIns.result}`:'Kayıt yok'}</div>{openIns.length>0&&<div className="sub warn">{openIns.length} bekleniyor</div>}</button>
        <button type="button" className="pl-fact" onClick={()=>go('talepler')}><div className="lab">Açık talep</div><div className="val">{openReq.length||'Yok'}</div></button>
      </div>
      <div className="pl-card" style={{marginTop:16}}><div className="pl-card-h"><h2>Başlangıç kontrol listesi</h2><span className="count">{doneSteps}/{steps.length}</span></div><div className="pl-card-b">
        {customer.status==='aktif'&&doneSteps<steps.length&&<div className="pl-alert" style={{margin:'6px 8px 10px'}}><span className="ic">!</span><span className="msg">Müşteri <b>aktif</b> ama başlangıç adımlarından <b>{steps.length-doneSteps}</b> tanesi eksik.</span></div>}
        <ul className="pl-checklist">{steps.map(([label,ok,tab,doc])=><li key={label} className={ok?'ok':''}><span className="mark" aria-hidden="true">{ok?'✓':'○'}</span><span className="grow">{label}</span>{!ok&&tab&&<button type="button" className="pl-linkbtn" onClick={()=>{if(doc)setDocType(doc);go(tab)}}>Tamamla →</button>}{!ok&&!tab&&<button type="button" className="pl-linkbtn" onClick={()=>setModal({kind:'customer'})}>Düzenle →</button>}<span className="sr-only">{ok?'tamam':'eksik'}</span></li>)}</ul>
      </div></div></>}
    {tab==='sozlesmeler'&&<div className="pl-card"><div className="pl-card-h"><h2>Sözleşmeler</h2><Link className="pl-btn pl-btn-ghost pl-btn-sm" to={`/panel/sozlesmeler?musteri=${id}`}>+ Sözleşme</Link></div><div className="pl-card-b">{data.contracts.length===0&&<div className="pl-empty">Kayıt yok.</div>}{data.contracts.map((x)=><div className="pl-row" key={x.id}><div className="grow"><b>{x.package}</b> · {fmtDate(x.start_date)}–{fmtDate(x.end_date)} · {fmtTL(x.price)} /{x.billing_period==='aylık'?'ay':'yıl'} · {x.status}</div>{x.end_date&&daysUntil(x.end_date)<=30&&<button className="pl-btn pl-btn-teal pl-btn-sm" onClick={()=>renew(x)}>Yenile</button>}</div>)}</div></div>}
    {tab==='faturalar'&&<div className="pl-card"><div className="pl-card-h"><h2>Faturalar</h2><button className="pl-btn pl-btn-ghost pl-btn-sm" onClick={()=>setModal({kind:'invoice',mode:'new',data:emptyInvoice(id)})}>+ Fatura kaydı</button></div><div className="pl-card-b">{data.invoices.length===0&&<div className="pl-empty">Kayıt yok.</div>}{data.invoices.map((x)=><div className="pl-row" key={x.id}><div className="grow"><div className="t1">{fmtTL(x.amount)} <InvoiceBadge row={x}/></div><div className="t2">{fmtDate(x.issue_date)} · son ödeme {fmtDate(x.due_date)}{x.note?` · ${x.note}`:''}{x.payment_link&&x.status!=='ödendi'?' · kart linki eklendi':''}{paidSource(x)?` · ${paidSource(x)}`:''}</div><div className="t2"><EDocCell row={x} onDone={load}/></div><ReviewNote row={x}/></div><div className="pl-actions">{x.status!=='ödendi'&&<><PaymentLinkButton row={x} onDone={load}/><PaymentMessageButton row={x} customer={customer}/><button className="pl-btn pl-btn-teal pl-btn-sm" title="Havale/nakit tahsilatı elle kapat" onClick={async()=>{if(await markPaid(x))load()}}>Ödendi (elle)</button></>}<button className="pl-btn pl-btn-ghost pl-btn-sm" onClick={()=>setModal({kind:'invoice',mode:'edit',data:{...x}})}>Düzenle</button></div></div>)}</div></div>}
    {tab==='belgeler'&&<div className="pl-card"><div className="pl-card-h"><h2>Belgeler</h2><div className="pl-actions"><select value={docType} onChange={(e)=>setDocType(e.target.value)} aria-label="Evrak türü">{DOC_TYPES.map((d)=><option key={d.v} value={d.v}>{d.l}</option>)}</select><label className="pl-btn pl-btn-ghost pl-btn-sm">{busy?'Yükleniyor…':'Evrak yükle'}<input hidden type="file" accept="image/*,application/pdf" disabled={busy} onChange={upload}/></label></div></div><div className="pl-card-b">{data.documents.length===0&&<div className="pl-empty">Evrak yok.</div>}{data.documents.map((x)=><div className="pl-row" key={x.id}><div className="grow"><div className="t1">{x.name}</div><div className="t2">{DOC_TYPES.find((d)=>d.v===x.type)?.l||x.type} · {fmtDate(x.created_at)}</div></div><SecureLink stored={x.file_url} target="_blank" rel="noreferrer">Aç ↗</SecureLink></div>)}</div></div>}
    {tab==='posta'&&<Section title="Posta & Kargo" rows={mailSorted} rowClass={(x)=>isOpenTebligat(x)?'pl-row-urgent':''} action={<Link className="pl-btn pl-btn-ghost pl-btn-sm" to={`/panel/kargo?musteri=${id}`}>+ Posta/kargo kaydı</Link>} render={(x)=><div style={{display:'flex',alignItems:'center',gap:10,flexWrap:'wrap'}}><span style={{flex:1,minWidth:180}}><span className={`pl-badge b-${x.type}`}>{x.type}</span> {x.sender||'—'} · {fmtDate(x.received_date)}{x.shelf?` · raf ${x.shelf}`:''}</span><select value={x.status} aria-label="Gönderi durumu" onChange={(e)=>mailStatus(x,e.target.value)}>{MAIL_STATUS.map((s)=><option key={s}>{s}</option>)}</select></div>}/>}
    {tab==='talepler'&&<div className="pl-card"><div className="pl-card-h"><h2>Talepler</h2></div><div className="pl-card-b">{data.requests.length===0&&<div className="pl-empty">Talep yok.</div>}{data.requests.map((x)=><div className="pl-row" key={x.id}><div className="grow"><div className="t1">{x.kind}</div><div className="t2">{x.note||'—'} · {fmtDate(x.created_at)}</div></div><select value={x.status} onChange={async(e)=>{await requests.update(x.id,{status:e.target.value});load()}}>{REQUEST_STATUS.map((s)=><option key={s}>{s}</option>)}</select></div>)}</div></div>}
    {tab==='yoklama'&&<Section title="Yoklama" rows={data.inspections} action={<Link className="pl-btn pl-btn-ghost pl-btn-sm" to={`/panel/yoklama?musteri=${id}`}>+ Yoklama kaydı</Link>} render={(x)=><div style={{display:'flex',alignItems:'center',gap:10,flexWrap:'wrap'}}><span style={{flex:1,minWidth:180}}>{fmtDate(x.date)}{x.officer?` · memur ${x.officer}`:''} · {x.note||'—'}</span><select value={x.result} aria-label="Yoklama sonucu" onChange={(e)=>insResult(x,e.target.value)}>{['bekleniyor','olumlu','olumsuz'].map((r)=><option key={r}>{r}</option>)}</select></div>}/>}
    </div>
    {modal?.kind==='customer'&&<CustomerForm title="Müşteriyi düzenle" initial={customer} partners={data.partners} onClose={()=>setModal(null)} onSave={saveCustomer}/>}
    {modal?.kind==='invoice'&&<InvoiceForm title={modal.mode==='new'?'Yeni fatura kaydı':'Fatura kaydını düzenle'} initial={modal.data} custs={[customer]} cts={data.contracts} lockCustomer onClose={()=>setModal(null)} onSave={saveInvoice}/>}
  </div>
}
function Section({title,rows,render,action,rowClass}){return <div className="pl-card"><div className="pl-card-h"><h2>{title}</h2>{action}</div><div className="pl-card-b">{rows.length===0&&<div className="pl-empty">Kayıt yok.</div>}{rows.map((x)=><div className={`pl-row ${rowClass?.(x)||''}`} key={x.id}><div className="grow">{render(x)}</div></div>)}</div></div>}
